language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: 1cZht+zoTxJCZJQvqMRwe9sAs6xVbBrcGRfg3WAs8KG5SFjNyEveJ7P2fsL7zmRCW0ufMqeMBFkk78IPU3B4GcdSVCmwhTs3RlpZ0vcOnj9NTAaH6R5m/1mxrjhtl6bs5ickuqU2xeJYKCdC0TX7fpQoCIwxePhsfur6o8R/uo1IiMUVWJs3KeG1oJS4YMm4YIfGewORO+Bu3DXv1dUlESkLpvXrCl6SKfTAERApWrA5s53fvg57cK4dhQmQlZ9gBBJ6yjejvJtqSUlPcXjhL26jVc27chOki6DMD2iQkv9AlWOiDSEXkOQkp5G0uflxWZEljrmmtATO89h4UBymutJQnhK+nijb2PIlFNo7pLs1hCOhtnU1xTd4Yb+zRyVTaosPjRZQlngTtzWo2FeoJ4TbiZ8hKZ+35fXt0wwIfLgaeIK2LXz/TPPuckJOHZvhM+Ovbe4ChJDYCZI0K9Va9vuQvdaO24k8nxlJhYHGaKKhihC33tzxyDpdvUFogjbnlVpT3UmzUiEV6anpIALQA0UTvzFhc7yUXvNP6CPAhozN8tjID6un58ifg0xFLaNKGfWpgc5V/+6VgvpaorsAVBPIlXWkeCQZmjQ8rdGovYBidK3203/D6HKbjsotQQziDJuedDckLNvZ5xN1G3k/T/0Y29jzxjP5lN2OJjj+fbU=
